from enum import Enum


class SubmissionState(str, Enum):
    SUBMISSION_UPLOADED = "SUBMISSION_UPLOADED"
    VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS"
    VALIDATION_WITH_ERRORS = "VALIDATION_WITH_ERRORS"
    VALIDATION_WITH_WARNINGS = "VALIDATION_WITH_WARNINGS"
    VALIDATION_SUCCESSFUL = "VALIDATION_SUCCESSFUL"
    SUBMISSION_SIGNED = "SUBMISSION_SIGNED"


class FilingState(str, Enum):
    FILING_STARTED = "FILING_STARTED"
    FILING_IN_PROGRESS = "FILING_IN_PROGRESS"
    FILING_COMPLETE = "FILING_COMPLETE"


class FilingType(str, Enum):
    MANUAL = "MANUAL"
